CREATE DATABASE Bike_store;

USE Bike_store;

SELECT * FROM brands;
SELECT * from categories;
SELECT * FROM customers;
SELECT * FROM order_items;
SELECT * FROM orders;
SELECT * FROM products;
SELECT * FROM staffs;
SELECT * FROM stocks;
SELECT * FROM stores;


-- Removing special characters from the Phone column in the Staff table --

UPDATE staffs
SET phone = REGEXP_REPLACE(phone, '[^0-9]', '');

/*Basic SQL Queery


/*We want to send a localized email campaign. 
Pull a list of the first names, last names, and emails of all customers 
who live in the state of 'NY' and the city of 'Buffalo'.*/

SELECT first_name,
last_name,
email
FROM customers
WHERE  state = 'NY' and city = 'Buffalo';


/*: The HR manager needs a list of all active employees 
(where active = 1) who currently work at Store ID 2. 
Return their names and phone numbers.*/

SELECT first_name,phone
FROM staffs
WHERE active = 1;

/*Show me the first 10 order line items 
where the discount applied was 20% (0.20) or higher. 
Return the Order ID, Product ID, and the discount.*/

SELECT order_id, product_id,discount
FROM order_items
WHERE discount >=0.2
LIMIT 10;


/*Fetch all orders that were placed between January 1, 2016, and March 31, 2016.
 Sort them by the order date from newest to oldest.*/

SELECT * FROM orders
WHERE order_date BETWEEN
'2016-01-01' and '2016-03-01';

/*: List the product names and prices of all Mountain Bikes
 (Category ID 6) that cost more than $1,500. 
 Sort the results by price, from most expensive to least.*/

SELECT product_name,list_price 
FROM products
WHERE category_id = 6 and list_price > 1500
ORDER BY list_price DESC;

/*How many total customers do we have in each state? 
Return the State abbreviation. 
the total count of customers in that state.*/

SELECT  state,
COUNT('customer_id') AS total_customers
FROM customers
GROUP BY state;

/*Which store (using store_id) has processed
the highest number of orders overall? Group by the Store ID and count the orders.*/

SELECT * from orders

SELECT store_id,
count('order_id') AS order_count
FROM orders
GROUP BY store_id
ORDER BY order_count DESC
LIMIT 1;

/*What is the maximum, minimum, and average list price of all the products we sell?*/



SELECT MAx(list_price) AS highest_prize,
MIN(list_price) AS minimum_prize,
AVG(list_price) AS average_prize
FROM products;

/*We want to know which brands dominate our catalog
Count how many products belong to each brand_id. 
Only display the brands that have more than 15 products in our catalog.*/


SELECT brand_id,
COUNT(*) AS brand_count
FROM products
GROUP BY brand_id
HAVING COUNT(*) > 15;

/*What is the total combined quantity of all bicycles currently
 sitting in stock at Store ID 1?*/

SELECT store_id,
  SUM(quantity) AS total_quantity
FROM stocks
WHERE store_id = 1;

/*JOIN in SQL

/*The product table only has a brand_id, which isn't helpful for non-technical staff. 
Write a query that returns the product_name and its corresponding actual brand_name*/

SELECT b.brand_name,p.product_name
FROM products  AS p  
LEFT JOIN brands AS b   
on p.brand_id = b.brand_id

/*Return a list showing the first name and last name of every staff member, 
right next to the actual store_name of the store they work at.*/

SELECT  s.first_name,s.last_name,
st.store_name
FROM staffs AS s
INNER JOIN stores AS st
on st.store_id = s.store_id;

/*For Order ID 5, list the actual names of the products purchased, 
the quantity bought, and the list price of each item.*/

SELECT p.product_name,oi.quantity,
oi.list_price
FROM order_items AS oi 
INNER JOIN products  AS p
on p.product_id = oi.product_id
WHERE oi.order_id = 5;


/*Return a list showing customer first and last names, 
along with the order_id and order_date of any orders they have placed.*/

SELECT o.order_id,c.first_name,c.last_name,
o.order_date
FROM customers  AS c
INNER JOIN orders AS o 
on c.customer_id = o.customer_id; 

/*Calculate the total gross revenue generated by each specific store_name.*/

SELECT s.store_name,
SUM(oi.quantity * oi.list_price) AS gross_revenue
FROM stores AS s
INNER JOIN orders AS o
    ON s.store_id = o.store_id
INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY s.store_name
ORDER BY gross_revenue DESC;

/*subquerry sql */

/*We need the names and prices of all products whose list price
is greater than the overall average list price of our catalog.*/



SELECT product_name,list_price
 FROM products
 WHERE list_price > ( SELECT AVG(list_price) 
 FROM products);

 /*retrieve a list of all order_ids and order_dates for orders placed by customers
  living in the 'NY' (New York) state.*/


SELECT order_id,order_date
FROM orders 
WHERE customer_id 
IN (SELECT customer_id
    FROM customers          
WHERE state = 'NY');

/*Retrieve the product_name and model_year for products strictly 
in the 'Mountain Bikes' category.*/



select product_name,model_year
  FROM products
WHERE category_id IN 
  (
    SELECT category_id
FROM categories
WHERE category_name = 'Mountain Bikes'
  )


/*We want the first_name, last_name, and email of those "ghost"
 customers who have never placed a single order to date.*/

SELECT first_name,last_name,email
FROM customers 
WHERE customer_id 
  NOT IN  (SELECT customer_id
FROM orders)



/*We need every customer's first_name, last_name, and a new column 
showing the total number of orders they have placed*/

SELECT 
    first_name,
    last_name,
    (
        SELECT COUNT(*)
        FROM orders o
        WHERE o.customer_id = c.customer_id
    ) AS total_orders
FROM customers c;


/* CASE STATEMENT

/*The marketing team is launching targeted email 
campaigns and wants to classify all items  into easy-to-understand price tiers */


SELECT product_name,
       list_price,
  CASE   
      WHEN list_price < 500 THEN 'Budget'
      WHEN list_price >= 500 AND list_price <= 2000 THEN 'Mid-Range'
      WHEN list_price > 2000 THEN 'Premium'
  END price_segment
FROM products;

/*: The backend database stores the order_status as raw numeric digits ($1, 2, 3, 4$).
 The customer support department needs a user-friendly report with readable text instead of codes
*/
SELECT * FROM orders;

SELECT order_id,
       customer_id,
       order_date,
  CASE
       WHEN order_status = 1 THEN 'pending'
       WHEN order_status = 2 THEN 'processing'
       WHEN order_status = 3 THEN 'Rejected'
       WHEN order_status = 4 THEN 'Completed'
       ELSE 'Unknown'
  END status_description
FROM orders;

/*•	Business Context: Human Resources needs a clean roster 
indicating active staff members versus
those who are currently inactive or on extended leave.*/

SELECT staff_id,
       first_name,
   CASE 
        WHEN active = 0 THEN 'Inactive'
        WHEN active = 1 THEN 'Active'
   END employment_status
FROM staffs;

/*Executive leadership wants to evaluate year-over-year revenue performance for each store. 
They need a report that displays revenue for the years 2016, 2017, and 2018 
side-by-side in a single row for every store.

Task

Using the stores, orders, and order_items tables:

Join the required tables.
Group the results by store_name.
Use conditional aggregation (SUM combined with a CASE statement based on the year of order_date) 
to create the following revenue columns:
revenue_2016
revenue_2017
revenue_2018*/

SELECT * FROM stores;
SELECT * FROM orders;
SELECT * FROM order_items;

SELECT s.store_name,
      SUM(
        CASE 
             WHEN YEAR (o.order_date)=2016 
             THEN  oi.quantity*oi.list_price * (1-oi.discount)
        END
      ) AS revenue_2016,

      SUM(
        CASE 
             WHEN YEAR (o.order_date)=2017
             THEN  oi.quantity*oi.list_price * (1-oi.discount)
        END
      ) AS revenue_2017,
       SUM(
        CASE 
             WHEN YEAR (o.order_date)=2018
             THEN  oi.quantity*oi.list_price * (1-oi.discount)
        END
      ) AS revenue_2018
FROM stores AS s 
INNER JOIN orders AS o
   ON s.store_id = o.store_id
INNER JOIN order_items  AS oi 
   ON o.order_id = oi.order_id
GROUP BY s.store_name; 

/*Business Request:
The Sales Strategy team wants to identify the company's highest-value customers for a new loyalty rewards program.
 To support this initiative,calculate the total net lifetime spending of each customer,
 taking discounts into account, and categorize customers into loyalty tiers based on their total spending.*/


SELECT c.customer_id,
      c.first_name,
      c.last_name,
    
    SUM(oi.quantity * oi.list_price *(1-discount)) AS total_spent,
   
   
  CASE 
       WHEN SUM(oi.quantity * oi.list_price *(1-discount)) > 5000 
       THEN 'VIP Tier'
       WHEN SUM(oi.quantity * oi.list_price *(1-discount)) >= 1500 AND 
           SUM(oi.quantity * oi.list_price *(1-discount)) <= 5000 
       THEN 'Frequnt_Tier'
       WHEN SUM(oi.quantity * oi.list_price *(1-discount)) < 1500
       THEN 'Standard Tier'
       ELSE 'Nothing'
  END AS loyalty_tier
FROM customers AS c
INNER JOIN 
   orders o 
ON c.customer_id = o.customer_id
INNer JOIN 
    order_items AS oi
ON oi.order_id = o.order_id
GROUP BY c.customer_id,
         c.first_name,
         c.last_name
ORDER BY total_spent DESC;

/*The supply chain manager needs to monitor fulfillment efficiency to see which store location is struggling with late shipments.
Join the stores and orders tables. Focus only on completed shipments (where shipped_date is not null). For each store*/

SELECT 
    s.store_name,

    COUNT(
        CASE
            WHEN o.shipped_date <= o.required_date
            THEN 1
        END
    ) AS on_time_count,

    COUNT(
        CASE
            WHEN o.shipped_date > o.required_date
            THEN 1
        END
    ) AS late_count

FROM stores s
INNER JOIN orders o
    ON s.store_id = o.store_id

WHERE o.shipped_date IS NOT NULL

GROUP BY s.store_name;